### ISSUE TITLE
az acr run can't login after acr enable private endpoint link

### ISSUE THREAD

**Issue by shuminxu01** [Azure/acr-cli#122]
**Describe the bug**
after we disabled public endpoint of acr and enabled the privated endpoint.
we can't run the "az acr run --cmd "acr purge --filter 'bmp/order:.*' --ago 0d --untagged --keep 2" --registry {registry name} /dev/null"

**To Reproduce**
1. disble public endpoint
2. run the "az acr run --cmd "acr purge --filter 'bmp/order:.*' --ago 0d --untagged --keep 2" --registry {registry name} /dev/null"

**Expected behavior**
the command can clear the image

**Screenshots**

**Any relevant environment information**
 - OS: Windows
 - Version 2.16.0

**Additional context**
the output information 

2022/08/08 08:07:02 Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.
2022/08/08 08:07:02 Creating Docker network: acb_default_network, driver: 'bridge'
2022/08/08 08:07:02 Successfully set up Docker network: acb_default_network
2022/08/08 08:07:02 Setting up Docker configuration...
2022/08/08 08:07:03 Successfully set up Docker configuration
2022/08/08 08:07:03 Logging in to registry: {registryname}.azurecr.cn
failed to login, ran out of retries: failed to set docker credentials: Error response from daemon: Get "https://{registryname}.azurecr.cn/v2/": denied: client with IP '40.73.169.192' is not allowed access. Refer https://aka.ms/acr/firewall to grant access.
: exit status 1
Run ID: fa2j failed after 6s. Error: failed during run, err: exit status 1

**Comment by northtyphoon** [comment]
It's by design. You can enable [trusted service with managed identity](https://learn.microsoft.com/en-us/azure/container-registry/allow-access-trusted-services#example-acr-tasks) to access registry with network restriction.

**Comment by georgejdli** [comment]
If you don't want to open up the firewall you can set up an ACR task agent pool in a virtual network with access to the ACR private endpoint:
https://learn.microsoft.com/en-us/cli/azure/acr/agentpool?view=azure-cli-latest

Then specify the agent pool in the acr run command
`az acr run --registry <your_registry> --agent-pool <your_agent_pool> --cmd $PURGE_CMD /dev/null`
