### ISSUE TITLE
Purge task reads repository name regex as literal

### ISSUE THREAD

**Issue by samjpv** [Azure/acr-cli#125]
I am currently automating creation of a scheduled ACR purge task in terraform using the following CLI command:
`steps: 
    - cmd: mcr.microsoft.com/acr/acr-cli:0.4 purge --filter '.*:.*' --ago 30d --keep 20 --untagged
        disableWorkingDirectoryOverride: true
        timeout: 21600`

I created this over 3 months ago, and at the time, it was working as expected (purging for every repository and every image/manifest of every version aside from the most recent 20 or those younger than 30 days).
 
Recently, I've started seeing this in the purge task run logs:
`Unable to find image 'mcr.microsoft.com/acr/acr-cli:0.4' locally
0.4: Pulling from acr/acr-cli
21c83c524219: Already exists
6ac28caa25f2: Pulling fs layer
527a2db38f69: Pulling fs layer
6ac28caa25f2: Verifying Checksum
6ac28caa25f2: Download complete
527a2db38f69: Verifying Checksum
527a2db38f69: Download complete
6ac28caa25f2: Pull complete
527a2db38f69: Pull complete
Digest: sha256:c61d4d91b72db340f0d0017f1d7de3dcfcdc127e7f5c03d379c0b428fa939154
Status: Downloaded newer image for mcr.microsoft.com/acr/acr-cli:0.4
Deleting tags for repository: .*
.* repository not found
Deleting manifests for repository: .*
.* repository not found`

It appears that the purge task is recognizing the repository name as a literal instead of as regex. I initially thought the "downloaded newer image" log meant that a newer image restricting regex usage in some way was released and it was downloading that instead of 0.4, but as far as I can tell, 0.4 is still the most recent version. If the same version of the CLI is being used as when I created the scheduled task months ago, then I'm confused as to why it would be working then but not now. I mentioned terraform for context, but I don't believe it is related to the issue. Is there something obvious I'm doing wrong here or a change that has been implemented to ignore regex in repo names?

**To Reproduce**
1. Run the CLI command above 

**Expected behavior**
The CLI command should be purging every repository and every image/manifest of every version aside from the most recent 20 or those younger than 30 days

**Comment by northtyphoon** [comment]
does "mcr.microsoft.com/acr/acr-cli:0.5" work as expected?

**Comment by samjpv** [comment]
Sorry for super delayed response - this does work with cli version 0.5.
