### ISSUE TITLE
`acr purge --untagged` should skip oci artifact manifest if its subject manifest still exists

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-cli#133]
**What is the problem you're trying to solve**
1. Attach an oci artifact `sha256:dd9c4a48ed770c2a25d541dffaa4030bf372a0fd461e4dc59eea87af4b9f81fa` to an image `myregistry.azurecr.io/bitnami/kafka:3.2`

oras discover -o tree myregistry.azurecr.io/bitnami/kafka:3.2
3.2
├── application/spdx+json
│   └── `sha256:dd9c4a48ed770c2a25d541dffaa4030bf372a0fd461e4dc59eea87af4b9f81fa`

2. The artifact manifest `sha256:dd9c4a48ed770c2a25d541dffaa4030bf372a0fd461e4dc59eea87af4b9f81fa` should not be purged if its subject image manifest `myregistry.azurecr.io/bitnami/kafka:3.2` still exists. 

**Describe the solution you'd like**

Skip purging the oci artifact manifiest if its subject manifest still exists.

**Comment by Korijn** [comment]
This is a pretty serious **bug**, not an `enhancement`. It's deleting more than it should!

**Comment by jaehnem** [comment]
This is also a problem for us.
