### ISSUE TITLE
Annotate command not added to root command handler

### ISSUE THREAD

**Issue by AsafAlgawi-MSFT** [Azure/acr-cli#336]
**Describe the bug**
The annotate command had been merged but not added to the root command handler thus making it unavailble.

**To Reproduce**
1. Try execute an annotate command

**Expected behavior**
The matching images should receive an annotation.

**Screenshots**
![image](https://github.com/user-attachments/assets/af401911-904f-4119-87ad-81127fb1a87c)

**Any relevant environment information**
 - OS: Linux
 - Version 0.12

**Comment by AsafAlgawi-MSFT** [comment]
It can be seen in the root handler for the CLI: https://github.com/Azure/acr-cli/blob/main/cmd/acr/root.go#L45
that the annotate command is not part of the cli.

**Comment by northtyphoon** [comment]
If you pass env `ACR_EXPERIMENTAL_ANNOTATE=true`, you should be able to see the command. For example,

`docker run -it -e ACR_EXPERIMENTAL_ANNOTATE=true mcr.microsoft.com/acr/acr-cli:
0.12 annotate`
