### ISSUE TITLE
Windows: make sure authentication works

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-cli#41]
Make sure the Windows authentication works for Tasks

**Comment by ggonzalere** [comment]
I have tried it running in windows by just running the binary and it works, also it works when it is run inside a windows task

**Comment by ehotinger** [comment]
@ggonzalere if it works inside a Windows task are you going to PR the Dockerfile for it, otherwise how'd you test it?

**Comment by ggonzalere** [comment]
Yes! I have the dockerfile done but I have another open PR so I was waiting for that to be checked in before checking in the windows dockerfile
