### ISSUE TITLE
Capital letters in tagged push result in error

### ISSUE THREAD

**Issue by scniro** [Azure/acr-cli#61]
**Describe the bug**
Pushing to `acr` seems to throw erroneous errors with capitalized tagging 

**To Reproduce**
```bash
$ az acr login --name="foo"
$ docker pull nginx
$ docker tag nginx myRegistry.azurecr.io/nginx
$ docker push
```

Results in

> unauthorized: authentication required

While..

```bash
[...]
$ docker tag nginx myregistry.azurecr.io/nginx
$ docker push
```
succeeds...

The only diff is, `myRegistry` => `myregistry`

**Expected behavior**
Push irregardless of capitalization

**Any relevant environment information**
 - OS: macOS Catalina 10.15.1

**Comment by juliusl** [comment]
@scniro Hello, this isn't an acr-cli issue. You should file this bug at the main ACR doc repo: 

https://github.com/azure/acr/issues

Thanks.
