### ISSUE TITLE
acr purge based on a retained number of images rather than --ago 

### ISSUE THREAD

**Issue by UniperMaster** [Azure/acr-cli#69]
**What is the problem you're trying to solve**
I want to purge a number of repositories but may want to retain atleast the last x number of images

I can't schedule a task based on --ago as the images could be quite stable and it could eventually be deleted as it exceeds the time duration  

**Describe the solution you'd like**
--retain 10    -- last 10 images

**Comment by timja** [comment]
Hi 👋 

I've created a PR for this: https://github.com/Azure/acr-cli/pull/72

please take a look and provide any feedback / testing on it

You can build it by running the `make binaries` command.
