### ISSUE TITLE
Purge command fails when repo contains locked images

### ISSUE THREAD

**Issue by tandrup** [Azure/acr-cli#70]
**Describe the bug**
Purge command fails if writes are disabled but deletes enabled.

**To Reproduce**
1. Disable writes for a tag using: `az acr repository update  --name <registry> --image mads:test --write-enabled false --delete-enabled true
2. Run the purge command: az acr run --cmd "acr purge --filter 'mads:.*' --untagged --ago 0d" --registry <registry> /dev/null       
3. Fails with this output:
```
Deleting tags for repository: mads
Error: failed to purge tags: acr.BaseClient#DeleteAcrTag: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="Unknown" Message="Unknown service error" Details=[{"errors":[{"code":"REGISTRY_DISALLOWED_OPERATION","detail":{},"message":"The operation is disallowed on this registry, repository or image. View troubleshooting steps at https://aka.ms/acr/faq/#why-does-my-pull-or-push-request-fail-with-disallowed-operation"}]}]
2020/06/22 07:57:28 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: ch2 failed after 5s. Error: failed during run, err: exit status 1
Run failed
```

**Expected behavior**
Would expect to delete the tag because deletes are enabled.

**Any relevant environment information**
 - OS: Mac OS X but the command was run using `az acr run ...`

**Comment by wju-MSFT** [comment]
Please assign to me.

**Comment by wju-MSFT** [comment]
Duplicated issue here: https://github.com/Azure/acr-cli/issues/134
Now the expected behavior is to skip purging the manifest/tag when its `--write-enabled` is set to `false`.
