### ISSUE TITLE
keep flag is not unknown when using Purge command within ACR Tasks

### ISSUE THREAD

**Issue by camal-cakar-gcx** [Azure/acr-cli#75]
**Describe the bug**
I am referring to this documentation on Azure https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge that `ACR` Tasks are using the `acr-cli` beneath and I saw in the source code that the `acr-cli` is providing a `keep` flag which fits perfectly into my use case.

We want to have the x latest tags from a container image but remove the others on regular basis.

We injecting any command containing the `keep` flag, the task fails and the logs show that the argument could not be found.

**To Reproduce**
1. Create an ACR
2. Prepare any command using `keep` for example `PURGE_CMD="acr purge --keep 2"`
3. Run command `az acr run --cmd "$PURGE_CMD" --registry $REGISTRY /dev/null`

**Expected behavior**
The keep flag is excepted and the task runs successfully.

**Actual Logs**
```
Queued a run with ID: xxx
Waiting for an agent...
2020/11/03 08:47:07 Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.
2020/11/03 08:47:07 Creating Docker network: acb_default_network, driver: 'bridge'
2020/11/03 08:47:07 Successfully set up Docker network: xxx_xxx_network
2020/11/03 08:47:07 Setting up Docker configuration...
2020/11/03 08:47:08 Successfully set up Docker configuration
2020/11/03 08:47:08 Logging in to registry: $REGISTRY.azurecr.io
2020/11/03 08:47:09 Successfully logged into $REGISTRY.azurecr.io
2020/11/03 08:47:09 Executing step ID: xxx_step_0. Timeout(sec): 600, Working directory: '', Network: 'xxx_xxx_network'
2020/11/03 08:47:09 Launching container with name: xxx_step_0
Error: unknown flag: --keep
2020/11/03 08:47:10 Container failed during run: xxx_step_0. No retries remaining.
failed to run step ID: xxx_step_0: exit status 1
```

**Any relevant environment information**
OS Agnostic

**Additional context**
N/A

**Comment by timja** [comment]
We contributed this awhile back, there's no tags on this repo, I guess someone needs to push it to a container registry.

@Wwwsylvia

As a work around you can build this from source and publish it to your container registry (which is what we do)

https://github.com/hmcts/cnp-aks-pipelines/blob/master/scripts/cleanup-acr-from-old-prod-images.sh#L28

**Comment by camal-cakar-gcx** [comment]
Thanks @timja for mentioning this. Will use that workaround but it would be great to integrate it into the platform and documentation. I was so close to create some uneccessary glue code for just achieving this.

**Comment by Wwwsylvia** [comment]
Thanks @timja !
@camal-cakar-gcx Sorry for the confusion. We shall release a new version this week, and will let you know the updates.

**Comment by Wwwsylvia** [comment]
@camal-cakar-gcx @timja v0.3 released! You can get it by `docker pull mcr.microsoft.com/acr/acr-cli:0.3`

**Comment by timja** [comment]
cc @adusumillipraveen ^^
