### ISSUE TITLE
Error: unknown flag: --keep

### ISSUE THREAD

**Issue by themegaphoenix** [Azure/acr-cli#76]
Describe the bug
Tried to use the `--keep` tag but it says `unknown flag: --keep`
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge#use-the-purge-command

`az --version` gives;
 `azure-cli:2.14.2` `core:2.14.2` `telemetry 1.0.6`

To Reproduce
Steps to reproduce the behaviour:

`az acr run --cmd "acr purge --filter 'hello-world:1.*' --dry-run --keep 3" --registry registry /dev/null
`

Expected behavior
Delete all the images starting with `hello-world:1` in the registry named `registry` apart from the latest three

Actual outcome:
 'unknown flag: --keep'

Screenshots:
![image](https://user-images.githubusercontent.com/9766462/98835912-f14c2580-2438-11eb-92aa-13d9906e9d64.png)

**Comment by northtyphoon** [comment]
ACR Tasks have supported the keep option
