### ISSUE TITLE
MSI BearerAuthorizer doesn't work for the client in acr-cli/acr?

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/acr-cli#82]
**Describe the bug**

I am programing to call ACR with MSI auth. But I hit 401 unauthorized error when calling `GetAcrRepositories`:
```
Error: acr.BaseClient#GetAcrRepositories: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unknown" Message="Unknown service error" Details=[{"errors":[{"code":"UNAUTHORIZED","detail":[{"Action":"*","Name":"catalog","Type":"registry"}],"message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}]
```

**To Reproduce**
1. My code is like this
```
...
       msiConfig := auth.MSIConfig{
		Resource: azure.PublicCloud.ServiceManagementEndpoint,
		ClientID: "<my-msi-client-id>",
	}

	authorizer, err := msiConfig.Authorizer()
	if err != nil {
		return res, err
	}

	acrClient := acr.New(acrLoginURL)
	acrClient.Authorizer = authorizer

	lastRepository := ""
	for {
		repositories, err := acrClient.GetAcrRepositories(ctx, lastRepository, nil)
		if err != nil {
			logger.WithError(err).Error("list next batch of repositories failed")
			return res, err
		}
...
```
The `auth` package is https://github.com/Azure/go-autorest/blob/c7f947c0610de1bc279f76e6d453353f95cd1bfa/autorest/azure/auth/auth.go#L750

2. I can see the token getting correctly with tcpdump. And the token is valid that I can curl with it to do token exchange with my ACR.

3. BTW, I can succeed calling `GetAcrRepositories` with SP BasicAuthorizer.
```
       acrClient.Authorizer = autorest.NewBasicAuthorizer(
		"<my-sp-id>",
		"<my-sp-pwd>",
	)
```

4. Plus, azure cli with the msi works for me:
```
az login --identity -u <my-msi-resource-id>
az acr repository list -g <my-rg> -n <acr-name>
```

**Expected behavior**

Expect the MSI BearerAuthorizer working as BasicAuthorizer.

**Screenshots**

**Any relevant environment information**
 - OS: Ubuntu 18.04.4 LTS
 - go version: go1.16.6 linux/amd64
 -      github.com/Azure/go-autorest/autorest v0.11.18
        github.com/Azure/go-autorest/autorest/adal v0.9.13
        github.com/Azure/go-autorest/autorest/azure/auth v0.4.2
        github.com/Azure/go-autorest/autorest/azure/cli v0.3.1
        github.com/Azure/go-autorest/autorest/date v0.3.0
        github.com/Azure/go-autorest/autorest/to v0.4.0

**Additional context**

**Comment by northtyphoon** [comment]
Close this issue as it's about authentication to ACR. Please reopen the issue in https://github.com/Azure/acr/issues if you still have questions.
