### ISSUE TITLE
`az acr run` doesn't interpret `/dev/null` correctly on Windows with Git bash

### ISSUE THREAD

**Issue by Rashair** [Azure/acr-cli#87]
**Describe the bug**
When using `/dev/null` as source location, `az acr run` returns:
```
Source location should be a local directory path or remote URL.
```
on Git bash.
Same command works on PowerShell 7.2.0.

**To Reproduce**
Use this tutorial: https://docs.microsoft.com/en-gb/learn/modules/publish-container-image-to-azure-container-registry/6-build-run-image-azure-container-registry

**Expected behavior**
The command should ignore source directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/33404585/145717222-aa94b62f-6289-4089-bb9d-e4195fe00f1e.png)  

![image](https://user-images.githubusercontent.com/33404585/145717308-8c650151-49ce-48dd-b3dc-18b13e21cd58.png)

**Any relevant environment information**
 - OS: Windows 19043.1348
 - Version:  2.30.0
 - Git version:  2.34.1

**Additional context**

**Comment by mo-robert-purvis** [comment]
If you replace the `/dev/null` with `''` (an emply string in single-quote characters) then the hello world image will run.

**Comment by mloskot** [comment]
No, neither works I'm afraid, and none of the command samples from the Microsoft docs work for me:

- PowerShell throws `the following arguments are required: <SOURCE_LOCATION>`
![image](https://user-images.githubusercontent.com/80741/182470105-46f058a8-6354-4a93-aea6-91cd3ee7a644.png)

- Bash throws `Source location should be a local directory path or remote URL`
![image](https://user-images.githubusercontent.com/80741/182470298-37adf9b1-2aab-4ea9-9600-a4621aae2df0.png)

```
$ az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-firewall": "0.9.0"
  }
}
```

**Comment by mloskot** [comment]
https://github.com/Azure/acr-cli/issues/87#issuecomment-1203200754
> No, neither works I'm afraid, and none of the command samples from the Microsoft docs work for me:
> 
>     * PowerShell throws `the following arguments are required: <SOURCE_LOCATION>`
>       ![image](https://user-images.githubusercontent.com/80741/182470105-46f058a8-6354-4a93-aea6-91cd3ee7a644.png)

It turns out the PowerShell needs quoting of the double quote passed as empty parameter:

- This does NOT work

```
>  az acr run --registry mycr --cmd '$Registry/hello-world:x' ''
the following arguments are required: <SOURCE_LOCATION>
```

- This does work

```
>  az acr run --registry mycr --cmd '$Registry/hello-world:x' '""'
Queued a run with ID: dbn
Waiting for an agent..
```
I've updated to:
...

Today, I also updated Azure CLI from 2.38.0 to 2.39.0, so perhaps handling of `'""'` has been fixed in the latest.

**Comment by northtyphoon** [comment]
It's azure cli. Please reopen it in https://github.com/Azure/azure-cli/issues if you still have the issue.
