### ISSUE TITLE
Incorrect tag in Yaml tasks aliases

### ISSUE THREAD

**Issue by stan-sz** [Azure/acr-cli#98]
**Describe the bug**
On https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml#image-aliases the information says that `acr` points to `acr:0.1` Is this still accurate?

**Comment by northtyphoon** [comment]
Thanks for catching the issue. I sent a pr to doc to update it.

**Comment by northtyphoon** [comment]
The page has been updated to reflect current images in Tasks. We will update the doc once it's updated. Thanks again for the remind.
