### ISSUE TITLE
az acr build warnings

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/acr-cli#99]
**Describe the bug**

**To Reproduce**

root@debian10:~# cd acr-cli/

root@debian10:~/acr-cli# az acr build --image acr:latest --registry $MYACR --no-push --file Dockerfile .

Packing source code into tar to upload...
Excluding '.git' based on default ignore rules
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_0b518ca4ccc64eeab4f838eec7d9cbeb.tar.gz'...
Sending context (5.602 MiB) to registry: myacr...
Queued a build with ID: cgxr
Waiting for an agent...
2022/04/11 09:48:59 Downloading source code...
2022/04/11 09:49:00 Finished downloading source code
2022/04/11 09:49:01 Using acb_vol_88762e04-bdc0-426e-a5b1-cf3acdf4b5c9 as the home volume
2022/04/11 09:49:01 Setting up Docker configuration...
2022/04/11 09:49:01 Successfully set up Docker configuration
2022/04/11 09:49:01 Logging in to registry: myacr.azurecr.io
2022/04/11 09:49:02 Successfully logged into myacr.azurecr.io
2022/04/11 09:49:02 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2022/04/11 09:49:02 Scanning for dependencies...
2022/04/11 09:49:03 Successfully scanned dependencies
2022/04/11 09:49:03 Launching container with name: build
Sending build context to Docker daemon  21.35MB
Step 1/10 : FROM golang:1.17-alpine3.14 AS gobuild-base
1.17-alpine3.14: Pulling from library/golang
8663204ce13b: Pulling fs layer
f792083cb66d: Pulling fs layer
166b6af146ed: Pulling fs layer
e4b24c66de7e: Pulling fs layer
50e715718d09: Pulling fs layer
e4b24c66de7e: Waiting
50e715718d09: Waiting
166b6af146ed: Verifying Checksum
166b6af146ed: Download complete
f792083cb66d: Verifying Checksum
f792083cb66d: Download complete
8663204ce13b: Verifying Checksum
8663204ce13b: Download complete
8663204ce13b: Pull complete
f792083cb66d: Pull complete
50e715718d09: Verifying Checksum
50e715718d09: Download complete
166b6af146ed: Pull complete
e4b24c66de7e: Verifying Checksum
e4b24c66de7e: Download complete
e4b24c66de7e: Pull complete
50e715718d09: Pull complete
Digest: sha256:9e085c25a5928df75e13f9810139b004de862ec95e1987343a37573cee2d1874
Status: Downloaded newer image for golang:1.17-alpine3.14
 ---> ab2dd1c34b24
Step 2/10 : RUN apk add --no-cache      git     make
 ---> Running in abbf7cfdffdd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/7) Installing brotli-libs (1.0.9-r5)
(2/7) Installing nghttp2-libs (1.43.0-r0)
(3/7) Installing libcurl (7.79.1-r0)
(4/7) Installing expat (2.4.7-r0)
(5/7) Installing pcre2 (10.36-r0)
(6/7) Installing git (2.32.0-r0)
(7/7) Installing make (4.3-r0)
Executing busybox-1.33.1-r7.trigger
OK: 19 MiB in 22 packages
Removing intermediate container abbf7cfdffdd
 ---> 0adec2b90f7e
Step 3/10 : FROM gobuild-base AS acr-cli
 ---> 0adec2b90f7e
Step 4/10 : WORKDIR /go/src/github.com/Azure/acr-cli
 ---> Running in 9fe2cecd020a
Removing intermediate container 9fe2cecd020a
 ---> bdc63b31d991
Step 5/10 : COPY . .
 ---> 6e9d7f1f5e18
Step 6/10 : RUN make binaries && mv bin/acr /usr/bin/acr
 ---> Running in 2a66881e6735
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1,param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1,param2>...]
                          synonym for --dirstat=files,param1,param2...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --compact-summary     generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --full-index          show full pre- and post-image object names on the "index" lines
    --color[=<when>]      show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --abbrev[=<n>]        use <n> digits to display object names
    --src-prefix <prefix>
                          show the given source prefix instead of "a/"
    --dst-prefix <prefix>
                          show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --find-copies-harder  use unmodified files as source to find copies
    --no-renames          disable rename detection
    --rename-empty        use empty blobs as rename source
    --follow              continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol
                          ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --indent-heuristic    heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --color-moved[=<mode>]
                          moved lines of code are colored differently
    --color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --relative[=<prefix>]
                          when run from subdir, exclude changes outside and show relative paths
    -a, --text            treat all files as text
    -R                    swap two inputs, reverse the diff
    --exit-code           exit with 1 if there were differences, 0 otherwise
    --quiet               disable all output of the program
    --ext-diff            allow an external diff helper to be executed
    --textconv            run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       Output to a specific file

+ bin/acr
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/docker/docker v1.4.2-0.20200227233006-38f52c9fec82
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/spf13/cobra v0.0.5
go: downloading github.com/Azure/go-autorest/autorest v0.11.21
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.16
go: downloading github.com/golang-jwt/jwt/v4 v4.1.0
go: downloading github.com/docker/cli v0.0.0-20190506213505-d88565df0c2d
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/Azure/go-autorest/logger v0.2.1
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading golang.org/x/crypto v0.0.0-20201002170205-7f63de1d35b0
go: downloading github.com/docker/docker-credential-helpers v0.6.1
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.3.3
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/containerd/containerd v1.4.10
go: downloading google.golang.org/grpc v1.19.1
go: downloading github.com/morikuni/aec v0.0.0-20170113033406-39771216ff4c
go: downloading github.com/golang/protobuf v1.3.1
go: downloading google.golang.org/genproto v0.0.0-20190307195333-5fe7a883aa19
go: downloading github.com/gogo/protobuf v1.2.0
go: downloading github.com/gorilla/mux v1.6.2
go: downloading github.com/docker/go-metrics v0.0.0-20181218153428-b84716841b82
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/prometheus/client_model v0.0.0-20190115171406-56726106282f
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1

+ binaries
Removing intermediate container 2a66881e6735
 ---> 2669004e55b2
Step 7/10 : FROM alpine:3.14
3.14: Pulling from library/alpine
8663204ce13b: Already exists
Digest: sha256:06b5d462c92fc39303e6363c65e074559f8d6b1363250027ed5053557e3398c5
Status: Downloaded newer image for alpine:3.14
 ---> e04c818066af
Step 8/10 : RUN apk --update add ca-certificates
 ---> Running in 4993433ace56
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20211220-r0)
Executing busybox-1.33.1-r7.trigger
Executing ca-certificates-20211220-r0.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 4993433ace56
 ---> 22601949e2e1
Step 9/10 : COPY --from=acr-cli /usr/bin/acr /usr/bin/acr
 ---> c4fe66f39a44
Step 10/10 : ENTRYPOINT [ "/usr/bin/acr" ]
 ---> Running in b8eefd929a4c
Removing intermediate container b8eefd929a4c
 ---> e75d15b53eea
Successfully built e75d15b53eea
Successfully tagged myacr.azurecr.io/acr:latest
2022/04/11 09:49:44 Successfully executed container: build
2022/04/11 09:49:44 Step ID: build marked as successful (elapsed time in seconds: 41.677286)
2022/04/11 09:49:44 Populating digests for step ID: build...
2022/04/11 09:49:45 Successfully populated digests for step ID: build
2022/04/11 09:49:45 The following dependencies were found:
2022/04/11 09:49:45
- image:
    registry: myacr.azurecr.io
    repository: acr
    tag: latest
  runtime-dependency:
    registry: registry.hub.docker.com
    repository: library/alpine
    tag: "3.14"
    digest: sha256:06b5d462c92fc39303e6363c65e074559f8d6b1363250027ed5053557e3398c5
  buildtime-dependency:
  - registry: registry.hub.docker.com
    repository: library/golang
    tag: 1.17-alpine3.14
    digest: sha256:9e085c25a5928df75e13f9810139b004de862ec95e1987343a37573cee2d1874
  git: {}

Run ID: cgxr was successful after 47s

root@debian10:~/acr-cli#

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

**Comment by northtyphoon** [comment]
It's an azure cli issue as the acr build command by default exclude .git file when uploading to the agent. Please open the issue in https://github.com/Azure/azure-cli/issues
